export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'CHANGE_SEARCH_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'CHANGE_SEARCH_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'CHANGE_SEARCH_FAILED';
